### Ophalen van alle harvests
GET https://localhost:7214/api/Harvests
Accept: application/json

### Ophalen van 1 specifieke harvest
GET https://localhost:7214/api/Harvests/1
Accept: application/json

### Voeg een nieuwe harvest toe
POST https://localhost:7214/api/Harvests
Content-Type: application/json

{
  "cropType": "Corn",
  "quantity": 500.10,
  "harvestDate": "2025-09-01"
}

### Ophalen van onbestaande harvest 
GET https://localhost:7214/api/Harvests/9999
Accept: application/json



### Ophalen van farms waar een specifiek dier zit
GET https://localhost:7214/api/Animals/1/farms
Accept: application/json

### Ophalen van kandidaat-farms waar dier nog NIET zit
GET https://localhost:7214/api/Animals/1/farms-candidates
Accept: application/json

### Farms ophalen voor onbestaand dier 
GET https://localhost:7214/api/Animals/9999/farms
Accept: application/json



### Ophalen van de relatie tussen farm 1 en dier 1
GET https://localhost:7214/api/FarmAnimals/1/1
Accept: application/json

### Een dier toevoegen aan een farm
POST https://localhost:7214/api/FarmAnimals
Content-Type: application/json

{
  "animalId": 13,
  "farmId": 1,
  "count": 10
}

### Ophalen van onbestaande relatie 
GET https://localhost:7214/api/FarmAnimals/999/888
Accept: application/json

### GEFAALD: POST met ongeldige data
POST https://localhost:7214/api/FarmAnimals
Content-Type: application/json

{
  "animalId": 13,
  "farmId": 1,
  "count": "FoutieveTekst"
}


### Unauthorized PUT test

PUT https://localhost:7214/api/Farm/1
Content-Type: application/json

{
  "sizeInHectares": 250.75
}