### ophalen van alle harvests
GET https://localhost:7214/api/Harvests
Accept: application/json

### Voeg een harvest toe 
POST https://localhost:7214/api/Harvests
Content-Type: application/json

{
  "cropType": "Corn",
  "quantity": 500.10,
  "harvestDate": "2025-09-01"
}

### ophalen van farms op basis van animal id
GET https://localhost:7214/api/Farms/GetFarmsOfAnimal/2
Content-Type: application/json


### ophalen van farms die niet gelinked zijn met de animal
GET https://localhost:7214/api/Farms/GetAvailableFarmsOfAnimal/1
Content-Type: application/json

### legen van de relatie tussen farm en een animal
POST https://localhost:7214/api/Farms/CreateFarmAnimal
Content-Type: application/json

{
  "animalId": 13,
  "farmId": 1,
  "count": 10
}