### POST Harvest (unAuthorized)
POST https://localhost:7214/api/Harvests
Content-Type: application/json

{
  "cropType": "Corn",
  "quantity": 500.10,
  "harvestDate": "2025-09-01"
}

### POST Harvest (Authorized)
POST https://localhost:7214/api/Harvests
Content-Type: application/json
Cookie: .AspNetCore.Identity.Application=CfDJ8J6kXnQBMyxPiGWCYMmdsYrcQI2K325p2cAd6IuGiTnfXvfZPUTSOffwW8qk_UMVF_T8enTejfaGYbsg3mICYH-9G78P4hX2bUdzJkvJQTtHgGrBht5E1kKOuKyPb3ikzktzVqCnHfcCUxvkaoIl_jlNUU3sadWAe7vkf2B2pqKMACKH27mGBsLH3LSDhynqveA_3TIrF30ePlVFTZTJV-PKIgxB70nOyy1R0h4JgJTnxXBeysBlIUW8lcZlaTaC6Fs7F6SfWnMXebV76Zu34u8kNz1SErwztmDEWsiq3YBaYM44Lj87Zrkhxx8nAv_FDCmngXtnBP5wzONHFxSEVLsUb69p-PiHTwSSlYSmLMh8J1ULELowkd0hJxaddIT-V7YvKoElR-SU0SOe2mVWOIB-ddR5hUl6jl4KwM1U0DTFkwnn4wt_deYFkJxF15nogN-PHxdUfz0D02BOJnNRbVRAtcpU-htWrak_CPp0-B_dyavc3JUIba5p04lIKLzJLPsx5aR66AHuMnRdLq_YKyEUnDVSxR0MHUUWuMdn6mRWGK9yyszo6zGJNdny5L0H7-aJeQk8ZyowfEyquJWk_egdLjlYWWOgqtIvIBVFVhV3AX4gHCKLcit3W4Q5qOEIt-hYuAhBHahJtUuhRoB-71TeiPorHmLsdTjYjJO_ntB-xPVvRODV1pTfa1Id7vXH9K3EjpKsbXzQHwDReHp15y2kTmZu489JjNIzISK2_aKkftOSsMyg0q3Ma2NRaV9QIvYb2JBdPVjheSz2Wv83gUnKZL4Kjzjz4oM-Qi8Td5EIJ-jeufVMeXl7c7pPPIeiag

{
  "cropType": "Corn",
  "quantity": 500.10,
  "harvestDate": "2025-09-01"
}
